import { KPI } from "@/components/kpi";
import { RevenueChart } from "@/components/revenue-chart";
import { getServerSupabase } from "@/lib/server-supabase";

export const dynamic="force-dynamic";
function londonDate(value:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(value);}

export default async function RevenuePage(){
 const db=getServerSupabase();
 const {data:events}=db?await db.from("revenue_events").select("*,opportunities(title,product_name,traffic_30d,conversion_rate)").order("occurred_at",{ascending:false}):{data:[] as any[]};
 const rows=events||[]; const gross=rows.reduce((s:number,r:any)=>s+Number(r.gross_gbp||0),0); const fees=rows.reduce((s:number,r:any)=>s+Number(r.fee_gbp||0),0); const net=rows.reduce((s:number,r:any)=>s+Number(r.net_gbp||0),0);
 const chartData=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=londonDate(d);const value=rows.filter((r:any)=>londonDate(new Date(r.occurred_at))===key).reduce((s:number,r:any)=>s+Number(r.net_gbp||0),0);return {day:d.toLocaleDateString("en-GB",{weekday:"short",timeZone:"Europe/London"}),revenue:Number(value.toFixed(2))};});
 return <><div className="topbar"><div><div className="eyebrow">Feedback loop</div><h1>Revenue</h1><div className="sub">Verified revenue is attributed back to the opportunity that caused it.</div></div><div className="badge">{rows.length?`${rows.length} revenue events`:"Awaiting first sale"}</div></div><div className="grid kpis"><KPI label="Gross" value={`£${gross.toFixed(2)}`}/><KPI label="Recorded fees" value={`£${fees.toFixed(2)}`}/><KPI label="Net" value={`£${net.toFixed(2)}`}/><KPI label="Margin" value={gross?`${((net/gross)*100).toFixed(1)}%`:"—"}/></div><div className="grid two-col"><section className="card"><div className="section-title"><h2>Revenue curve</h2><span>last 7 days</span></div><RevenueChart data={chartData}/></section><section className="card"><div className="section-title"><h2>Ledger state</h2><span>learning inputs</span></div><div className="needs"><div className="need"><b>{rows.length}</b><div className="meta">verified revenue events</div></div><div className="need"><b>£{net.toFixed(2)}</b><div className="meta">net contribution currently recorded</div></div><div className="need"><b>{new Set(rows.map((r:any)=>r.opportunity_id).filter(Boolean)).size}</b><div className="meta">monetised opportunities</div></div></div></section></div><section className="card" style={{marginTop:16}}><div className="section-title"><h2>Attributed sales</h2><span>newest first</span></div><div className="table-wrap"><table><thead><tr><th>Opportunity</th><th>Product</th><th>Provider</th><th>Gross</th><th>Net</th><th>Occurred</th></tr></thead><tbody>{rows.length?rows.map((r:any)=><tr key={r.id}><td><strong>{r.opportunities?.title||"Unattributed"}</strong></td><td>{r.opportunities?.product_name||"—"}</td><td>{r.provider}</td><td>£{Number(r.gross_gbp).toFixed(2)}</td><td>£{Number(r.net_gbp).toFixed(2)}</td><td>{new Date(r.occurred_at).toLocaleString("en-GB")}</td></tr>):<tr><td colSpan={6} className="meta">No revenue has been recorded yet.</td></tr>}</tbody></table></div></section></>;
}
