import { Agent, Opportunity } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "opp_184",
    title: "Freelance mileage tracker spreadsheet",
    niche: "Small business",
    source: "vidIQ",
    score: 91,
    demand: 78,
    competition: 24,
    commercialIntent: 94,
    status: "published",
    product: "Mileage Tracker Pro",
    price: 7.99,
    monthlySearches: 18400,
    revenue30d: 126.8,
    traffic30d: 5931,
    conversionRate: 1.7,
    nextAction: "Expand into driver-specific variants",
  },
  {
    id: "opp_201",
    title: "Client onboarding checklist template",
    niche: "Freelancers",
    source: "vidIQ",
    score: 87,
    demand: 74,
    competition: 31,
    commercialIntent: 89,
    status: "production",
    product: "Client Launch Kit",
    price: 11,
    monthlySearches: 12100,
    revenue30d: 0,
    traffic30d: 0,
    conversionRate: 0,
    nextAction: "Generate landing page + video",
  },
  {
    id: "opp_219",
    title: "Simple CRM for solo consultants",
    niche: "Business software",
    source: "Opportunity Agent",
    score: 84,
    demand: 71,
    competition: 36,
    commercialIntent: 93,
    status: "approved",
    product: "Consultant CRM Lite",
    price: 19,
    monthlySearches: 9800,
    revenue30d: 0,
    traffic30d: 0,
    conversionRate: 0,
    nextAction: "Build MVP calculator + lead capture",
  },
  {
    id: "opp_231",
    title: "Weekly meal prep cost calculator",
    niche: "Personal finance",
    source: "Rising keywords",
    score: 79,
    demand: 82,
    competition: 48,
    commercialIntent: 72,
    status: "scored",
    product: "Meal Cost Planner",
    price: 5,
    monthlySearches: 22500,
    revenue30d: 0,
    traffic30d: 0,
    conversionRate: 0,
    nextAction: "Awaiting approval",
  },
  {
    id: "opp_240",
    title: "Wedding budget split calculator",
    niche: "Weddings",
    source: "YouTube search",
    score: 76,
    demand: 75,
    competition: 44,
    commercialIntent: 81,
    status: "discovered",
    product: "Wedding Budget Pack",
    price: 9,
    monthlySearches: 14700,
    revenue30d: 0,
    traffic30d: 0,
    conversionRate: 0,
    nextAction: "Run commercial-intent validation",
  },
];

export const agents: Agent[] = [
  { id: "research", name: "Scout", role: "Demand discovery", status: "running", autonomy: "green", lastRun: "2 min ago", output: "14 opportunities discovered" },
  { id: "scorer", name: "Judge", role: "Opportunity scoring", status: "running", autonomy: "green", lastRun: "4 min ago", output: "7 ideas scored above 75" },
  { id: "writer", name: "Forge", role: "Offer + content production", status: "idle", autonomy: "amber", lastRun: "18 min ago", output: "3 production packs completed" },
  { id: "video", name: "Studio", role: "Video factory", status: "idle", autonomy: "amber", lastRun: "41 min ago", output: "2 scripts ready for HeyGen" },
  { id: "publisher", name: "Launch", role: "Publishing + deployment", status: "attention", autonomy: "red", lastRun: "1 hr ago", output: "1 deployment needs approval" },
  { id: "analyst", name: "Ledger", role: "Revenue feedback loop", status: "running", autonomy: "green", lastRun: "1 min ago", output: "Winner cluster: business templates" },
];

export const dailyRevenue = [
  { day: "Mon", revenue: 26 },
  { day: "Tue", revenue: 41 },
  { day: "Wed", revenue: 33 },
  { day: "Thu", revenue: 58 },
  { day: "Fri", revenue: 49 },
  { day: "Sat", revenue: 72 },
  { day: "Sun", revenue: 64 },
];
